# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  node: circleci/node@1.0.1

jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - checkout
      - node/install-npm
  test:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - checkout
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test